name: build
children:
  - name: build
    children:
      - name: builder
      - name: building
      - name: buildable
      - name: rebuild
        children:
          - name: rebuilder
          - name: rebuilding
      - name: built
        children:
          - name: rebuilt
