// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Vocabulary struct {
	Name       string        `json:"name"`
	Meaning    string        `json:"meaning" yaml:"meaning,omitempty"`
	Tags       []string      `json:"tags" yaml:"tags,omitempty"`
	Constitute []string      `json:"constitute" yaml:"constitute,omitempty"`
	Children   []*Vocabulary `json:"children" yaml:"children,omitempty"`
}
