name: 1CEA
children:
  - name: west
    children:
      - name: western
      - name: northwest
        children:
          - name: northwestern
      - name: southwest
        children:
          - name: southwestern
      - name: Midwest
        children:
          - name: Midwestern
