package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/bonaysoft/engra/apis/graph/model"
)

// Vocabularies is the resolver for the vocabularies field.
func (r *queryResolver) Vocabularies(ctx context.Context, name string) (*model.Vocabulary, error) {
	panic(1)
	// return r.Find(name)
}

// Vocabulary is the resolver for the vocabulary field.
func (r *queryResolver) Vocabulary(ctx context.Context, name string) (*model.Vocabulary, error) {
	panic(fmt.Errorf("not implemented: Vocabulary - vocabulary"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
